//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace FileMakerToDB.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class FileMakerMigratedEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new FileMakerMigratedEntities object using the connection string found in the 'FileMakerMigratedEntities' section of the application configuration file.
        /// </summary>
        public FileMakerMigratedEntities() : base("name=FileMakerMigratedEntities", "FileMakerMigratedEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FileMakerMigratedEntities object.
        /// </summary>
        public FileMakerMigratedEntities(string connectionString) : base(connectionString, "FileMakerMigratedEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FileMakerMigratedEntities object.
        /// </summary>
        public FileMakerMigratedEntities(EntityConnection connection) : base(connection, "FileMakerMigratedEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DataImport> DataImports
        {
            get
            {
                if ((_DataImports == null))
                {
                    _DataImports = base.CreateObjectSet<DataImport>("DataImports");
                }
                return _DataImports;
            }
        }
        private ObjectSet<DataImport> _DataImports;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DataImports EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDataImports(DataImport dataImport)
        {
            base.AddObject("DataImports", dataImport);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FileMakerMigratedModel", Name="DataImport")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DataImport : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DataImport object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="row">Initial value of the row property.</param>
        /// <param name="column_name">Initial value of the column_name property.</param>
        public static DataImport CreateDataImport(global::System.Int64 id, global::System.Int64 row, global::System.String column_name)
        {
            DataImport dataImport = new DataImport();
            dataImport.id = id;
            dataImport.row = row;
            dataImport.column_name = column_name;
            return dataImport;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String path_name
        {
            get
            {
                return _path_name;
            }
            set
            {
                Onpath_nameChanging(value);
                ReportPropertyChanging("path_name");
                _path_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("path_name");
                Onpath_nameChanged();
            }
        }
        private global::System.String _path_name;
        partial void Onpath_nameChanging(global::System.String value);
        partial void Onpath_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 row
        {
            get
            {
                return _row;
            }
            set
            {
                OnrowChanging(value);
                ReportPropertyChanging("row");
                _row = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("row");
                OnrowChanged();
            }
        }
        private global::System.Int64 _row;
        partial void OnrowChanging(global::System.Int64 value);
        partial void OnrowChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String column_name
        {
            get
            {
                return _column_name;
            }
            set
            {
                Oncolumn_nameChanging(value);
                ReportPropertyChanging("column_name");
                _column_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("column_name");
                Oncolumn_nameChanged();
            }
        }
        private global::System.String _column_name;
        partial void Oncolumn_nameChanging(global::System.String value);
        partial void Oncolumn_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String data_context
        {
            get
            {
                return _data_context;
            }
            set
            {
                Ondata_contextChanging(value);
                ReportPropertyChanging("data_context");
                _data_context = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("data_context");
                Ondata_contextChanged();
            }
        }
        private global::System.String _data_context;
        partial void Ondata_contextChanging(global::System.String value);
        partial void Ondata_contextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String original_column
        {
            get
            {
                return _original_column;
            }
            set
            {
                Onoriginal_columnChanging(value);
                ReportPropertyChanging("original_column");
                _original_column = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("original_column");
                Onoriginal_columnChanged();
            }
        }
        private global::System.String _original_column;
        partial void Onoriginal_columnChanging(global::System.String value);
        partial void Onoriginal_columnChanged();

        #endregion
    
    }

    #endregion
    
}
