//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrightVision.DQControl.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrightVision.DQControl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap account {
            get {
                object obj = ResourceManager.GetObject("account", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap BE {
            get {
                object obj = ResourceManager.GetObject("BE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bg_cyan {
            get {
                object obj = ResourceManager.GetObject("bg_cyan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bg_pink {
            get {
                object obj = ResourceManager.GetObject("bg_pink", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bg_selector {
            get {
                object obj = ResourceManager.GetObject("bg_selector", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap bg_yellow {
            get {
                object obj = ResourceManager.GetObject("bg_yellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap cancel_16x16 {
            get {
                object obj = ResourceManager.GetObject("cancel_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap completed {
            get {
                object obj = ResourceManager.GetObject("completed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap contact {
            get {
                object obj = ResourceManager.GetObject("contact", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap DE {
            get {
                object obj = ResourceManager.GetObject("DE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap DK {
            get {
                object obj = ResourceManager.GetObject("DK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;GlobalValue&quot; : null,
        ///	&quot;Type&quot; : &quot;Dropbox&quot;,
        ///	&quot;Form&quot; : {
        ///		&quot;Settings&quot; : {
        ///			&quot;Label&quot; : &quot;[Sample label]&quot;,
        ///			&quot;QuestionText&quot; : &quot;[Sample question text]&quot;,
        ///			&quot;QuestionHelp&quot; : &quot;[Sample question help]&quot;,
        ///			&quot;Priority&quot; : &quot;Prio1&quot;,
        ///			&quot;PlotDoneStatus&quot; : &quot;Done&quot;,
        ///			&quot;DataBindings&quot; : {
        ///				&quot;account_level&quot;: false,
        ///				&quot;language_code&quot;: &quot;&quot;,
        ///				&quot;account_id&quot; : &quot;&quot;,
        ///				&quot;answer_id&quot; : &quot;&quot;,
        ///				&quot;contact_id&quot; : &quot;&quot;,
        ///				&quot;dialog_id&quot; : &quot;&quot;,
        ///				&quot;campaign_id&quot; : &quot;&quot;,
        ///				&quot;question_id&quot; : &quot;&quot;,
        ///				&quot;questions_text_languag [rest of string was truncated]&quot;;.
        /// </summary>
        public static string dropbox {
            get {
                return ResourceManager.GetString("dropbox", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap edit {
            get {
                object obj = ResourceManager.GetObject("edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap FI {
            get {
                object obj = ResourceManager.GetObject("FI", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap FR {
            get {
                object obj = ResourceManager.GetObject("FR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap help {
            get {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap info {
            get {
                object obj = ResourceManager.GetObject("info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap IT {
            get {
                object obj = ResourceManager.GetObject("IT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;GlobalValue&quot; : null,
        ///	&quot;Type&quot; : &quot;MultipleChoice&quot;,
        ///	&quot;Form&quot; : {
        ///		&quot;Settings&quot; : {
        ///			&quot;Label&quot; : &quot;[Sample label]&quot;,
        ///			&quot;QuestionText&quot; : &quot;[Sample question text]&quot;,
        ///			&quot;QuestionHelp&quot; : &quot;[Sample question help]&quot;,
        ///			&quot;Priority&quot; : &quot;Prio2&quot;,
        ///			&quot;PlotDoneStatus&quot; : &quot;Done&quot;,
        ///			&quot;DataBindings&quot; : {
        ///				&quot;account_level&quot;: false,
        ///				&quot;language_code&quot;: &quot;&quot;,
        ///				&quot;account_id&quot; : &quot;&quot;,
        ///				&quot;answer_id&quot; : &quot;&quot;,
        ///				&quot;contact_id&quot; : &quot;&quot;,
        ///				&quot;dialog_id&quot; : &quot;&quot;,
        ///				&quot;campaign_id&quot; : &quot;&quot;,
        ///				&quot;question_id&quot; : &quot;&quot;,
        ///				&quot;questions_text_ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string multiplechoice {
            get {
                return ResourceManager.GetString("multiplechoice", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap NL {
            get {
                object obj = ResourceManager.GetObject("NL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap NO {
            get {
                object obj = ResourceManager.GetObject("NO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ownership {
            get {
                object obj = ResourceManager.GetObject("ownership", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap PH {
            get {
                object obj = ResourceManager.GetObject("PH", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap required {
            get {
                object obj = ResourceManager.GetObject("required", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap save_16x16 {
            get {
                object obj = ResourceManager.GetObject("save_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;GlobalValue&quot; : null,
        ///	&quot;Type&quot; : &quot;Schedule&quot;,
        ///	&quot;Form&quot; : {
        ///		&quot;Settings&quot; : {
        ///			&quot;Label&quot; : &quot;[Sample label]&quot;,
        ///			&quot;QuestionText&quot; : &quot;[Sample question text]&quot;,
        ///			&quot;QuestionHelp&quot; : &quot;[Sample question help]&quot;,
        ///			&quot;Priority&quot; : &quot;Required&quot;,
        ///			&quot;PlotDoneStatus&quot; : &quot;Done&quot;,
        ///			&quot;CustomerOwnership&quot; : true,
        ///			&quot;BVOwnership&quot; : true,
        ///			&quot;DataBindings&quot; : {
        ///				&quot;account_level&quot; : false,
        ///				&quot;language_code&quot;: &quot;&quot;,
        ///				&quot;account_id&quot; : &quot;&quot;,
        ///				&quot;answer_id&quot; : &quot;&quot;,
        ///				&quot;contact_id&quot; : &quot;&quot;,
        ///				&quot;dialog_id&quot; : &quot;&quot;,
        ///				&quot;campaign_ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string schedule {
            get {
                return ResourceManager.GetString("schedule", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap SE {
            get {
                object obj = ResourceManager.GetObject("SE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;GlobalValue&quot; : null,
        ///	&quot;Type&quot; : &quot;SmartText&quot;,
        ///	&quot;Form&quot; : {
        ///		&quot;Settings&quot; : {
        ///			&quot;Label&quot; : &quot;[Sample label]&quot;,
        ///			&quot;QuestionText&quot; : &quot;[Sample question text]&quot;,
        ///			&quot;QuestionHelp&quot; : &quot;[Sample question help]&quot;,
        ///			&quot;Priority&quot; : &quot;Required&quot;,
        ///			&quot;PlotDoneStatus&quot; : &quot;Done&quot;,
        ///			&quot;CustomerOwnership&quot; : true,
        ///			&quot;BVOwnership&quot; : true,
        ///			&quot;DataBindings&quot; : {
        ///				&quot;account_level&quot;: false,
        ///				&quot;language_code&quot;: &quot;&quot;,
        ///				&quot;account_id&quot; : &quot;&quot;,
        ///				&quot;answer_id&quot; : &quot;&quot;,
        ///				&quot;contact_id&quot; : &quot;&quot;,
        ///				&quot;dialog_id&quot; : &quot;&quot;,
        ///				&quot;campaign_ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string smarttext {
            get {
                return ResourceManager.GetString("smarttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;GlobalValue&quot; : null,
        ///	&quot;Type&quot; : &quot;Textbox&quot;,
        ///	&quot;Form&quot; : {
        ///		&quot;Settings&quot; : {
        ///			&quot;Label&quot; : &quot;[Sample label]&quot;,
        ///			&quot;QuestionText&quot; : &quot;[Sample question text]&quot;,
        ///			&quot;QuestionHelp&quot; : &quot;[Sample question help]&quot;,
        ///			&quot;Priority&quot; : &quot;Required&quot;,
        ///			&quot;PlotDoneStatus&quot; : &quot;Done&quot;,
        ///			&quot;CustomerOwnership&quot; : true,
        ///			&quot;BVOwnership&quot; : true,
        ///			&quot;DataBindings&quot; : {
        ///				&quot;account_level&quot;: false,
        ///				&quot;language_code&quot;: &quot;&quot;,
        ///				&quot;account_id&quot; : &quot;&quot;,
        ///				&quot;answer_id&quot; : &quot;&quot;,
        ///				&quot;contact_id&quot; : &quot;&quot;,
        ///				&quot;dialog_id&quot; : &quot;&quot;,
        ///				&quot;campaign_id [rest of string was truncated]&quot;;.
        /// </summary>
        public static string textbox {
            get {
                return ResourceManager.GetString("textbox", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap UK {
            get {
                object obj = ResourceManager.GetObject("UK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
